name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "8652241c-19f0-4f3e-a01d-974c9ceca462"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "21dc328b9e82451492c996f91e089046"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
